version: "3.4"

volumes:
  db: {}

services:
  mysql:
    image: percona:5.7.22
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    ports: [ "127.0.0.1:33306:3306" ]
