version: "3.4"

volumes:
  db: {}

services:
  mysql:
    platform: linux/x86_64
    image: mariadb:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db:/var/lib/mysql
    ports: [ "127.0.0.1:33306:3306" ]
