name: Build
on: [push]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Run rubocop
        run: |
          bundle exec rubocop --parallel
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        database: [sqlite, postgres, mysql]
    services:
      mysql:
        image: percona:5.7.22
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 33306:3306
    env:
      TARGET_DB: ${{ matrix.database }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
      - name: Setup test database
        run: |
          bin/rails db:setup
      - name: Run tests
        run: bin/rails test
